---
apiVersion: v1
kind: Secret
metadata:
  name: {{ title }}
  {% if namespace -%}
  namespace: {{ namespace }}
  {% endif -%}
  {% if labels -%}
  labels:
    {{ labels | indent(4) }}
  {%- endif %}
type: kubernetes.io/tls
data:
  tls.crt: |
    {{ cert | wordwrap | indent(4) }}
  tls.key: |
    {{ key | wordwrap | indent(4) }}
