---
apiVersion: v1
kind: Secret
metadata:
  name: {{ title }}
  {% if namespace -%}
  namespace: {{ namespace }}
  {% endif -%}
  {% if labels -%}
  labels:
    {{ labels | indent(4) }}
  {%- endif %}
type: Opaque
stringData:
  {%- for key, value in data.items() %}
  {{ key }}: {{ value | indent(6) }}
  {%- endfor %}
